template: "ArmServer"

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console
#    - type: file
#      currentLogFilename: /tmp/textsecureshserver.log
#      archivedLogFilenamePattern: /temp/textsecureserver-%d.log.gz
#      archivedFileCount: 5
